# Generated by Django 3.2.23 on 2024-08-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20240810_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='country',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
