# Generated by Django 3.2.23 on 2024-08-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20240810_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='tenant',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tenant',
            field=models.EmailField(default='amatdany@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='position',
            name='tenant',
            field=models.EmailField(max_length=254),
        ),
    ]
