# Generated by Django 3.2.23 on 2024-08-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_tenant'),
        ('employees', '0005_alter_employee_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.ManyToManyField(blank=True, to='companies.Company'),
        ),
    ]
