# Generated by Django 3.2.23 on 2024-09-12 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_employee_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeverificationcode',
            name='is_used',
        ),
    ]
