# Generated by Django 3.2.23 on 2024-09-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_remove_employeeverificationcode_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='preferred_language',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
