# Generated by Django 3.2.23 on 2024-10-01 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20241001_2008'),
        ('employees', '0013_employee_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ubication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_ubication', to='companies.ubication'),
        ),
    ]
