# Generated by Django 3.2.23 on 2024-10-28 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_alter_ubication_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('tenant', models.EmailField(max_length=254)),
                ('require_validation', models.BooleanField(default=False)),
                ('require_addittional_info', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('company', models.ManyToManyField(to='companies.Company')),
            ],
        ),
        migrations.CreateModel(
            name='AbsenceEmployee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant', models.EmailField(max_length=254)),
                ('text', models.TextField()),
                ('validate', models.BooleanField(default=False)),
                ('filepath', models.FileField(upload_to='absences/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('absence_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clocks.absencetype')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
