# Generated by Django 3.2.23 on 2024-10-28 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clocks', '0002_absenceemployee_absencetype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absencetype',
            old_name='company',
            new_name='companies',
        ),
    ]
