# Generated by Django 3.2.23 on 2024-10-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clocks', '0003_rename_company_absencetype_companies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absenceemployee',
            name='filepath',
            field=models.FileField(blank=True, upload_to='absences/'),
        ),
    ]
