# Generated by Django 3.2.23 on 2024-11-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clocks', '0004_alter_absenceemployee_filepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absenceemployee',
            name='validate',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
