# Generated by Django 3.2.23 on 2024-11-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clocks', '0005_alter_absenceemployee_validate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absenceemployee',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
