from django.urls import path
from employees.api.views import ManagerListView,ManagerView,EmployeeListView,EmployeeView,EmployeeCompanyListView,EmployeeCompanyListLiteView,EmployeeCompaniesListView,EmployeeCompaniesListLiteView,AddCompanyToEmployeeView,RemoveCompanyFromEmployeeView,EmployeeByIdView,EmployeeStateView
from employees.api.views import DepartmentListView,DepartmentView,PositionListView,PositionView, DownloadDepartmentTemplateView,DownloadEmployeeTemplateView,DownloadPositionTemplateView,EmployeeListLiteView,EmployeeSendVerificationCodeForgetView,EmployeeSendVerificationCodeChangeView,EmployeeUpdateForgetPasswordView
from employees.api.views import UploadDepartmentFileView,UploadEmployeeFileView,UploadPositionFileView, EmployeeEmailVerificationView,CustomTokenObtainPairView,EmployeeUpdatePasswordView,DepartmentByCompanyListView,PositionByCompanyListView,EmployeeLiteView,EmployeeChangePreferedLanguageView
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView
urlpatterns = [
    path('auth/login', CustomTokenObtainPairView.as_view()),    
    path('auth/token/refresh',TokenRefreshView.as_view()),
    path('auth/token/verify',TokenVerifyView.as_view()),
    path('auth/me',EmployeeView.as_view()),
    path('auth/me/lite',EmployeeLiteView.as_view()),    
    path('auth/me/emailverified',EmployeeEmailVerificationView.as_view()),    
    path('auth/me/password',EmployeeUpdatePasswordView.as_view()),    
    path('auth/me/forgetpassword',EmployeeUpdateForgetPasswordView.as_view()), 
    path('auth/me/preferedlanguage',EmployeeChangePreferedLanguageView.as_view()),              
    path('auth/me/state',EmployeeStateView.as_view()),      
    path('managers', ManagerListView.as_view()),
    path('managers/<int:pk>', ManagerView.as_view()),    
    path('employees', EmployeeListView.as_view()),    
    path('employees/employeebyid/<int:pk>', EmployeeByIdView.as_view()),        
    path('employees/lite', EmployeeListLiteView.as_view()),        
    path('employees/companies', EmployeeCompaniesListView.as_view()),
    path('employees/companies/lite', EmployeeCompaniesListLiteView.as_view()),    
    path('employees/company', EmployeeCompanyListView.as_view()),
    path('employees/company/lite', EmployeeCompanyListLiteView.as_view()),       
    path('employees/<int:pk>/addcompany/<int:company_id>', AddCompanyToEmployeeView.as_view()),
    path('employees/<int:pk>/removecompany/<int:company_id>', RemoveCompanyFromEmployeeView.as_view()),
    path('employees/download-employee-template/', DownloadEmployeeTemplateView.as_view()),       
    path('employees/upload-employee-template/', UploadEmployeeFileView.as_view()),              
    path('departments', DepartmentListView.as_view()),
    path('departments/<int:pk>', DepartmentView.as_view()), 
    path('departments/bycompany/<int:company_id>', DepartmentByCompanyListView.as_view()),     
    path('department/download-department-template/', DownloadDepartmentTemplateView.as_view()),      
    path('department/upload-department-template/', UploadDepartmentFileView.as_view()),             
    path('positions', PositionListView.as_view()),
    path('positions/<int:pk>', PositionView.as_view()),  
    path('positions/bycompany/<int:company_id>', PositionByCompanyListView.as_view()),                      
    path('position/download-position-template/', DownloadPositionTemplateView.as_view()),                                    
    path('position/upload-position-template/', UploadPositionFileView.as_view()),       
    path('verifyemail/<str:token>', EmployeeEmailVerificationView.as_view()),     
    path('sendverificationcodeforget', EmployeeSendVerificationCodeForgetView.as_view()),       
    path('sendverificationcodechange', EmployeeSendVerificationCodeChangeView.as_view()),           
]