# Generated by Django 3.2.23 on 2024-10-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_ubication'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubication',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
