# Generated by Django 3.2.23 on 2024-10-01 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_ubication_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ubication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
