# Generated by Django 3.2.23 on 2024-10-28 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_ubication_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubication',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ubications', to='companies.company'),
        ),
    ]
