# Generated by Django 3.2.23 on 2024-08-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='tenant',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='scheduledetail',
            name='tenant',
            field=models.EmailField(max_length=254),
        ),
    ]
