# Generated by Django 3.2.23 on 2024-08-15 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20240811_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='notification_ids',
            new_name='notification_channels_ids',
        ),
    ]
