# Generated by Django 3.2.23 on 2024-08-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_rename_notification_ids_schedule_notification_channels_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledetail',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
