# Generated by Django 3.2.23 on 2024-10-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_alter_scheduledetail_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='geolocation_required',
            field=models.BooleanField(default=False),
        ),
    ]
